#SPDX-License-Identifier: MIT-0
---
- name: Yubikey LUKS | Setup
  ansible.builtin.include_tasks:
    file: install.yaml
    apply:
      tags:
        - luks
        - yubikey_luks_setup
  tags:
    - luks
    - yubikey_luks_setup

- name: Yubikey LUKS | Enroll Yubikey
  ansible.builtin.include_tasks:
    file: enroll.yaml
    apply:
      tags:
        - luks
        - yubikey_luks_enroll
  when: yubikey_luks_enroll
  tags:
    - luks
    - yubikey_luks_enroll
